Невозможно отменить заказы #18943

	У дилера из Ленинградской есть два заказа которые он не может отменить.

	dp пишет ошибку, что нельзя завершить уже завершенный заказ.

		По логике все верно.

	В админке в заказах статус "Завершено", а отображается в "необходимо связаться с покупателем".

	Смотреть на признак need_to_call.

	Вопросы:

		Где должны отображаться заказы со статусом "Отменен"?

			В разделе "Все заказы".

	orders_order - id - 157172

	Причина возникновения бага:

		Завершенный заказ не может быть завершен, пока диллер не нажал кнопку "Созвонились".

		Дмитрий Малашыхин говорит, что это ненормальное поведение и что возможно они когда то давно при тестировании допустили косяк.

		Сейчас этот косяк нужно исправить и давать возможность диллеру отменять заказ даже если он не созвонился с заказчиком.

	orders/urls/__init__.py

		wrapper_need_to_call_orders_view

	orders/views/arm.py

		NeedToCallOrdersView

Защита от DDOS атаки яндекса #17614

	Когда робот яндекса сходит с ума, он начинает запрашивать фид по несколько раз в секунду... это ложит наш ресурс...

	Необходимо лимитировать запросы...

	Небоходимо отправлять об этом письмо. И после того, как ситуация нормализовалась.

	Вопросы:

		Что такое фид?

			Фид - это файл, содержащий в себе информацию о товаре или услуге. 

			Может быть нескольких форматов: YML, XML, CSV,  GZ, TSV, ZIP.

		Где в snr урл, который отдает файл с фидом?

			modules/main/__init__.py

			    url(r'^yandex_market/{}/(?P<subdomain>\w+).yml$'

		Как получить руками файл с фидом?

			Перейти по адресу http://127.0.1.1:8100/yandex_market/8319d51f-98d2-4b2a-992d-a2ab5461effa/anapa.yml

		Где место, которое формирует фид?

			main/views/market.py

				YandexMarketView

					engine/views/main/market.py

						YandexMarketView -> BaseYml -> TemplateView

		Что нужно отправить яндекс роботу, чтобы правильно отбить его запрос?

		Если ддос повторяется из минуты в минуту, развер нормально спамить наших ответственны и что мы будем делать, если они попросят остановить этот спам?

	Что

		Лимитировать запросы яндекса.

		Если больше какого то кол-ва в минуту, то блокируем.

		Потом отправляем письмо диллерам и админам.

		Если атака остановилась, то опять отправляем диллерам и админам письмо, а яндексу разрешаем обращаться.

Закрыть возможность создавать пользователей с одинаковым email 18347

	create

		url(r'^create/(?P<event_uuid>[0-9a-f|-]+)/$', create_customer, name='api_create_customer')

		http://127.1.0.1:8300/api/customer/create/4097a061-d6ae-4655-9823-84f7e83cbcd9

		dp_package/profile/form.py -> 

			class BaseCreateCustomerForm(RenderFormMixin, DateBirthValidationMixin

				def clean_email(self):

	auth

		url(r'^auth/$', authorization_customer, name='api_auth_customer')

		dp_package/profile/form.py 

			class AuthCustomerForm(RenderFormMixin, forms.Form):

				def clean_email(self):

	request

		import requests

		requests.post('http://127.1.0.1:8300/api/customer/create/4097a061-d6ae-4655-9823-84f7e83cbcd9/', data = {'name': 'Ilya3', 'email': 'KADUK_IA@km-union.ru', 'password': 'asdf1234'})

		def create_customer_handler(post):

			...

			print create_customer_form.errors

	Вопросы:

		Все уже есть, в чем тогда проблема?

	Что

		Валидацию на почту.

		Имя почты одинаковое с верхним регистром, должно выдавать ошибку.

	Как

		Проверяем почту.

		Если есть символы в верхнем регистре, то показываем ошибку.

		Если нет, то разрешаем создать.

	Как

		re.findall(r'[A-ZА-Я]', a)

Посадочная страница

	- все, что они хотят размесить согласовать Зелюков Анатолий

	- если все ок, мы берем в работу

	- создать задачу в мега плане

	- подключить Виктора


Проблема с апи MoneyCare, 17835

	def check_status_order_in_money_care():

	    for mc_order in money_care_orders:
	        order = mc_order.order
	        response = requests.get(
	            url.format(settings.MONEY_CARE_URL, mc_order.mc_id),
	            headers=auth_header
	        )
	        print reponse
	        print auth_header

	Все ок.

	Сервер где находится https://mc1.moneycare.su установил сертификат.

	Dp делает запрос, получает в ответ сертификат, проверяется его в центре.

	Если не валидные выкидывает ошибку.

		Из модуля requests

			"Requests verifies SSL certificates for HTTPS requests, just like a web browser. By default, SSL verification is enabled, and Requests will throw a SSLError if it’s unable to verify the certificate"

Исправить отчет с состоянием обработки заказа, 18349

	Заказы диллера

		http://127.1.0.1:8300/orders/?dealer_site=67

	Состояние заказа

		http://127.1.0.1:8300/dpa/orders/orderprocessstate/123372/change/?_changelist_filters=q%3D146308

	Отчет

		http://127.1.0.1:8300/reports/

	Название отчета

		"Отчет об ошибках" или "Отчет об ошибках по заказам" (более подробный).

	Поддомен

		stavropol.korallmicro.ru

	Время

		с 14 по 18 февраля 2019

	Учет времени обработки заказа

		Модель class OrderProcessTime(models.Model):

	Статус заказа

		Модель class OrderProcessState(models.Model):

		Создается/изменяется при создании/изменении заказа.

		По умолчанию заказ фиксируется как неошибочный.

	В коде

		modules/report/views.py

			class Report(FormView):
				def form_valid(self, form):
					REPORT_MAPPER.get(report_type)

						total-orders-errors

							modules/report/views.py

								'total-orders-errors': reports.OrderErrorByClientReport,

									class OrderErrorByClientReport(BaseReport, SimpleHeaderMixin):
										def _render_data(self, block_render, report_options):

											...

											error_times_dict = OrderProcessState.objects
											
	Модель, где хранится состояние заказа

		class OrderProcessState(models.Model):

		OrderProcessState.objects.get(order_id=146308).error_start_time

	Вопросы Малашихина:

		Ставится ли стоп, когда диллер нажал "не дозвонился"?

		А если через 3 дня нажал "дозвонился" то как считается время?

	Проверка

		Берем готовый заказ

			163821

			http://127.1.0.1:8300/dpa/orders/order/163821/change/

			http://127.1.0.1:8300/dpa/orders/orderprocessstate/?q=163821

			http://127.1.0.1:8300/orders/?dealer_site=67

			Сброс времени начала обработки

				ord_process_state = OrderProcessState.objects.get(order_id=163821)

				ord_process_state - 140844

				ord_process_time = OrderProcessTime.objects.get(state_id=ord_process_state.pk)

			OrderProcessState.objects.select_for_update().get(order_id=order_id)

		Нажимаем "не дозвонился"

		Смотрим что произошло

			Скорее всего проблема в этих условиях

				# если превышено время обработки и когда заказ обработан
	            if order_process_state.has_error and finish_order_processing:
	                order_process_state.error_finish_time = current_time
	                update_fields.append('error_finish_time')


	            # если остановлен по расписанию оператора
	            if order_process_state.stopped_by_operators_schedule:
	                order_process_state.stopped_by_operators_schedule = False
	                update_fields.append('stopped_by_operators_schedule')


	            if update_fields:
	                order_process_state.save(update_fields=update_fields)

	Вопросы:

		Что происходит, когда пользователь нажал "не дозвонился"?

		Пробовал на заказе 163821.

			{'url': r'^submit/(?P<order_id>\d+)/(?P<action>[\w_]+)/$', 'wrapper_view': wrapper_order_submit_view},

				class OrderSubmitView(NotAllowed404View, ApiMixIn):

					def need_to_call(self, request, order):

					    end_order_process_time.send(Order, order_id=order.id, reason_alias='NEED_TO_CALL')

					    	def end_process_time_handler(sender, order_id, **kwargs):

					    		order_process_state = OrderProcessState.objects.select_for_update().get(order_id=order_id)

Проблема с выгодными предложениями magic

	http://magic.km-union.ru/catalog/offertype/35/change/

	https://www.korallmicro.ru/products/offer/35?utm_source=site&utm_medium=banner_mainpage&utm_campaign=category&utm_term=allactions

		def sync_offers(site_models=SITE_MODELS, shop_type=CURRENT_SHOPPING_TYPE):

		def ones_sync_offers_by_shop(shopping_type):

		def get_json_offertypes(request):

		def set_show_on_main_offertype(request, offertype_pk, show_on_main_value):

		def sync_offers_korallmicro():

	http://magic.km-union.ru/catalog/catalog/318144/change/

	https://www.korallmicro.ru/catalog/portativnaya_tekhnika/vneshnie_akkumulyatory

		class InfoCatalog(models.Model):

		class CatalogAdmin(admin.ModelAdmin):

		def sync_catalogs_and_products(site_models=SITE_MODELS, shop_type=CURRENT_SHOPPING_TYPE):

		def update_infocatalog(sender, **kwargs):

		def create_default_info_catalog(shop_type):

		!!!!!!!!!!!!

		catalog/tasks

			def sync(shop_type=settings.DEFAULT_SHOPPING_TYPE):

			6a5d63c8bb18fb4d

			6a5d63c8bb18fb4d

			[2019-07-25 13:43:47,848: ERROR/MainProcess] Task sync_shop[4f66da87-344e-44e8-8c7c-237dcf8b6a3f] raised unexpected: IntegrityError(1452, 'Cannot add or update a child row: a foreign key constraint fails (`magic`.`catalog_distributions`, CONSTRAINT `product_id_refs_code_6a5d63c8bb18fb4d` FOREIGN KEY (`product_id`) REFERENCES `catalog_products` (`code`))')

		Коралл берет нужные данные из

			Базы korallmicro

				SELECT * FROM public.catalogs WHERE name = 'Внешние аккумуляторы';

			class CatalogController

				public function indexAction(){

					$renderedProductItems = $product->renderProductItemsByAlias($alias, $renderParams['type'], $renderParams['sort'], $renderParams['is_dealer_provided'], $renderParams['sort_direction']);

					var_dump($alias, $renderParams['type'], $renderParams['sort'], $renderParams['is_dealer_provided'], $renderParams['sort_direction']); die();

		Что записывает туда данные?

			def sync_catalogs_and_products(site_models=SITE_MODELS, shop_type=CURRENT_SHOPPING_TYPE):

-----------------------------------------------------------------------------------

	- dp, Новый отчет, 17621; ломакин;

	- use case magic, для будущих функциональных тестов, 18755; к глубокову за консультацией "как работает"

	по задачам отписываться причастным;

-------------

Когда в 1с узлы обмена новые позиции для синхронизации в мэджик и если их много, то мэд шлет смс

	